version: '3.8'

services:
  # Redis - для Sidekiq и кэширования
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5



  # Rails Backend
  backend:
    build:
      context: ./rails_backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY_HERE
    volumes:
      - ./rails_backend:/rails
      - rails_bundle:/usr/local/bundle
      - sqlite_data:/rails/storage
    depends_on:
      redis:
        condition: service_healthy
    command: sh -c "bundle install && rm -f /rails/tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Sidekiq - для фоновых задач
  sidekiq:
    build:
      context: ./rails_backend
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY_HERE
    volumes:
      - ./rails_backend:/rails
      - rails_bundle:/usr/local/bundle
      - sqlite_data:/rails/storage
    depends_on:
      redis:
        condition: service_healthy
    command: sh -c "bundle install && bundle exec sidekiq"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data:
  sqlite_data:
  rails_bundle:
  frontend_node_modules:
